/**
 * Template Conversation Flow definitions.
 *
 * Per AGENTS.md invariants:
 *   #3  Published flows are immutable — to change a flow we create a new
 *       version then publish (the SDK's `update` semantics handle the
 *       versioning).
 *   #5  No vertical-specific logic outside `blueprints/` — these flow
 *       definitions live in the provisioning script, not in the runtime
 *       request path. The runtime injects per-call dynamic variables; the
 *       flow structure is identical across calls.
 *   #6  Outcomes are real — every terminal node has a corresponding
 *       custom-function tool node (book_meeting, log_objection,
 *       report_stage_change). The classifier reads tool-call logs.
 *   #7  Voice provider is Retell config — the flow JSON doesn't name
 *       Cartesia. Voice is set on the Agent that references this flow.
 *
 * Structure:
 *   ice-break (conversation)
 *     → discovery (conversation)
 *       → pitch (conversation)
 *         → objection (conversation, may loop)
 *           → close (conversation)
 *             → book_meeting (function: success_event)
 *             → log_objection (function: classifier)
 *             → end
 *   plus a global `report_stage_change` tool available at every node.
 *
 * Hand-authored from Retell's published flow schema (validated by SDK at
 * create-time). NOT generated by an LLM at runtime — invariant #2 forbids
 * slow work in the call path. If you need to refine these, edit the JSON
 * here and re-run the provisioning script.
 */

import type Retell from "retell-sdk";

type FlowCreateParams = Retell.ConversationFlowCreateParams;
type FlowNode = FlowCreateParams["nodes"][number];
type FlowTool = NonNullable<FlowCreateParams["tools"]>[number];

interface BuildArgs {
  /** The blueprint's vertical_id, embedded as a flow-wide variable. */
  verticalId: string;
  /** Disclosure line to inject into ice-break (empty string = none). */
  disclosureLine: string;
  /** Win condition's success-event tool name. */
  successEvent: string;
  /** Persona archetype id (default; overridable per call). */
  defaultArchetype: string;
  /**
   * Public origin where the webhook routes live (e.g.
   * `https://cell4u.vercel.app`). Retell does NOT template-render tool
   * URLs at call time, so we bake the concrete value at provision time.
   */
  toolWebhookUrl: string;
}

interface IntakeBuildArgs {
  toolWebhookUrl: string;
}

/* -------------------------------------------------------------------------- */
/* Tool definitions                                                           */
/* -------------------------------------------------------------------------- */

function reportStageChangeTool(toolUrl: string): FlowTool {
  return {
    type: "custom",
    name: "report_stage_change",
    description:
      "Call whenever the conversation enters a new pipeline stage. Used by the war-room dashboard to update the tile state.",
    url: toolUrl,
    speak_during_execution: false,
    speak_after_execution: false,
    parameters: {
      type: "object",
      properties: {
        stage: {
          type: "string",
          enum: ["ice_break", "discovery", "pitch", "objection", "closing"],
          description: "Which stage the conversation just entered.",
        },
      },
      required: ["stage"],
    },
  };
}

function logObjectionTool(toolUrl: string): FlowTool {
  return {
    type: "custom",
    name: "log_objection",
    description:
      "Call when the lead expresses an objection. Classify it so the dashboard can route the tile to the correct terminal state.",
    url: toolUrl,
    speak_during_execution: false,
    speak_after_execution: false,
    parameters: {
      type: "object",
      properties: {
        classification: {
          type: "string",
          enum: ["not_interested", "callback", "do_not_call"],
        },
        reason: { type: "string" },
      },
      required: ["classification"],
    },
  };
}

function bookMeetingTool(successEvent: string, toolUrl: string): FlowTool {
  return {
    type: "custom",
    name: successEvent,
    description:
      "Call ONLY when the lead has explicitly agreed to a meeting time. This is the win condition — never call it speculatively.",
    url: toolUrl,
    speak_during_execution: false,
    speak_after_execution: true,
    parameters: {
      type: "object",
      properties: {
        when: {
          type: "string",
          description: "ISO 8601 datetime the lead agreed to.",
        },
        attendee_name: { type: "string" },
        attendee_email: { type: "string" },
        notes: { type: "string" },
      },
      required: ["when"],
    },
  };
}

function detectBlueprintTool(toolUrl: string): FlowTool {
  return {
    type: "custom",
    name: "detect_blueprint",
    description:
      "Call early in intake once you know which vertical the user is working in. The server uses the returned id to choose the correct dynamic_var_schema to fill.",
    url: toolUrl,
    speak_during_execution: false,
    speak_after_execution: false,
    parameters: {
      type: "object",
      properties: {
        vertical_id: {
          type: "string",
          enum: ["b2b_local_services", "real_estate_acquisition"],
        },
        confidence: { type: "number" },
      },
      required: ["vertical_id"],
    },
  };
}

/* -------------------------------------------------------------------------- */
/* Call flow (per-vertical structure)                                         */
/* -------------------------------------------------------------------------- */

function callFlowNodes(args: BuildArgs): FlowNode[] {
  const { disclosureLine } = args;
  const opener = disclosureLine
    ? `${disclosureLine}\n\n{{persona_opener}}`
    : "{{persona_opener}}";

  const nodes: FlowNode[] = [
    {
      id: "ice_break",
      type: "conversation",
      instruction: {
        type: "prompt",
        text: opener,
      },
      edges: [
        {
          id: "ice_break_to_discovery",
          destination_node_id: "discovery",
          transition_condition: {
            type: "prompt",
            prompt:
              "The lead has acknowledged the call and is willing to keep talking.",
          },
        },
        {
          id: "ice_break_to_objection",
          destination_node_id: "objection",
          transition_condition: {
            type: "prompt",
            prompt: "The lead pushed back, asked who is calling, or expressed reluctance.",
          },
        },
      ],
    },
    {
      id: "discovery",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Ask one short qualifying question relevant to {{target_descriptor}}. Listen. Do not pitch yet. Keep it under 25 seconds.",
      },
      edges: [
        {
          id: "discovery_to_pitch",
          destination_node_id: "pitch",
          transition_condition: {
            type: "prompt",
            prompt: "You have a useful qualifying signal.",
          },
        },
        {
          id: "discovery_to_objection",
          destination_node_id: "objection",
          transition_condition: {
            type: "prompt",
            prompt: "The lead pushed back or asked to be removed.",
          },
        },
      ],
    },
    {
      id: "pitch",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Deliver the offer in {{persona_voice}} style. One sentence on what {{seller_business_name}} does, one on the outcome, one on the ask. Reference {{offer}}.",
      },
      edges: [
        {
          id: "pitch_to_close",
          destination_node_id: "close",
          transition_condition: {
            type: "prompt",
            prompt: "The lead is positive or curious about next steps.",
          },
        },
        {
          id: "pitch_to_objection",
          destination_node_id: "objection",
          transition_condition: {
            type: "prompt",
            prompt: "The lead is hesitant, deflecting, or actively pushing back.",
          },
        },
      ],
    },
    {
      id: "objection",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Handle the objection in {{persona_voice}} style with one reframe and one question. If the lead says they want to be left alone or removed from the list, call log_objection with classification do_not_call and end the call politely. Do not pressure.",
      },
      edges: [
        {
          id: "objection_to_close",
          destination_node_id: "close",
          transition_condition: {
            type: "prompt",
            prompt: "The lead's objection was answered and they are open to a next step.",
          },
        },
        {
          id: "objection_to_end",
          destination_node_id: "end_polite",
          transition_condition: {
            type: "prompt",
            prompt:
              "The lead is firm (not interested, do not call, busy). Wrap politely.",
          },
        },
      ],
    },
    {
      id: "close",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Ask for the {{win_cta}}. Be specific about time and channel. If they agree, call the success-event tool with the agreed time before ending the call.",
      },
      edges: [
        {
          id: "close_to_end",
          destination_node_id: "end_call",
          transition_condition: {
            type: "prompt",
            prompt: "The lead has committed to the next step or has declined.",
          },
        },
      ],
    },
    {
      id: "end_call",
      type: "end",
    },
    {
      id: "end_polite",
      type: "end",
    },
  ];

  return nodes;
}

/* -------------------------------------------------------------------------- */
/* Intake flow                                                                */
/* -------------------------------------------------------------------------- */

function intakeFlowNodes(): FlowNode[] {
  return [
    {
      id: "ice_break",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Greet the user. Tell them this will take about two minutes and you'll ask a few questions about their business.",
      },
      edges: [
        {
          id: "ice_break_to_detect",
          destination_node_id: "detect",
          transition_condition: {
            type: "prompt",
            prompt: "The user has acknowledged and is ready to answer.",
          },
        },
      ],
    },
    {
      id: "detect",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Ask: 'In one sentence, what does your business sell, and who do you sell to?' Listen carefully. From the answer infer whether this is a B2B local-services campaign (selling to local SMBs) or a real-estate acquisition campaign (buying residential property). Then call detect_blueprint with the inferred vertical_id and confidence. Never call it speculatively. If the answer is ambiguous, ask one more clarifying question first.",
      },
      edges: [
        {
          id: "detect_to_collect",
          destination_node_id: "collect",
          transition_condition: {
            type: "prompt",
            prompt: "detect_blueprint has been called and returned successfully.",
          },
        },
      ],
    },
    {
      id: "collect",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Ask one question at a time to fill the dynamic_var_schema for the detected vertical. The server will inject the field prompts via dynamic variables on the next agent turn. Confirm each answer briefly before moving on.",
      },
      edges: [
        {
          id: "collect_to_ready",
          destination_node_id: "ready",
          transition_condition: {
            type: "prompt",
            prompt: "Every required field in the dynamic_var_schema has a value.",
          },
        },
      ],
    },
    {
      id: "ready",
      type: "conversation",
      instruction: {
        type: "prompt",
        text:
          "Summarize the campaign back in two sentences. Ask: 'Ready to deploy?' If yes, end the call. If they want to change something, return to collect.",
      },
      edges: [
        {
          id: "ready_to_end",
          destination_node_id: "end_call",
          transition_condition: {
            type: "prompt",
            prompt: "The user confirmed ready to deploy.",
          },
        },
        {
          id: "ready_to_collect",
          destination_node_id: "collect",
          transition_condition: {
            type: "prompt",
            prompt: "The user wants to change a value.",
          },
        },
      ],
    },
    {
      id: "end_call",
      type: "end",
    },
  ];
}

/* -------------------------------------------------------------------------- */
/* Build payloads                                                             */
/* -------------------------------------------------------------------------- */

export function buildCallFlow(args: BuildArgs): FlowCreateParams {
  return {
    start_speaker: "agent",
    start_node_id: "ice_break",
    model_choice: {
      type: "cascading",
      // Fast model in the call loop per AGENTS.md "Model routing defaults".
      // Choices are constrained to Retell's enum; gpt-5-mini is the closest
      // match to the stated default. Override per-node for the objection
      // node in Ticket 6 if desired.
      model: "gpt-5-mini",
    },
    global_prompt: [
      "You are an outbound voice sales agent.",
      `Vertical: ${args.verticalId}.`,
      `Default persona archetype: ${args.defaultArchetype}.`,
      "Be concise. Never invent customer history. Never claim to be human.",
      "If the lead asks if you are an AI, say yes.",
      "Stop talking the moment the lead starts speaking.",
    ].join("\n"),
    nodes: callFlowNodes(args),
    tools: [
      reportStageChangeTool(args.toolWebhookUrl),
      logObjectionTool(args.toolWebhookUrl),
      bookMeetingTool(args.successEvent, args.toolWebhookUrl),
    ],
    default_dynamic_variables: {
      cell4u_marker: `cell4u/${args.verticalId}/call/v1`,
      persona_opener: "Hi — is this a good moment for a quick call?",
      persona_voice: "calm, direct, friendly",
      target_descriptor: "the lead's situation",
      seller_business_name: "your business",
      offer: "our service",
      win_cta: "a short follow-up call",
    },
  };
}

export function buildIntakeFlow(args: IntakeBuildArgs): FlowCreateParams {
  return {
    start_speaker: "agent",
    start_node_id: "ice_break",
    model_choice: {
      type: "cascading",
      model: "gpt-5-mini",
    },
    global_prompt: [
      "You are an intake agent for the Cell For You platform.",
      "Your job is to detect the user's vertical and collect the fields the chosen blueprint needs.",
      "Be brief, friendly, and confirm each answer before moving on.",
    ].join("\n"),
    nodes: intakeFlowNodes(),
    tools: [detectBlueprintTool(args.toolWebhookUrl)],
    default_dynamic_variables: {
      cell4u_marker: "cell4u/intake/v1",
    },
  };
}
